app:
  name: rangine
  env: debug
  server: http
server:
  http:
    host: 0.0.0.0
    port: 8084
log:
  default:
    driver: stream
    path: run.log
    level: debug
database:
  default:
    driver: mysql
    user_name: ${MYSQL_USERNAME-root}
    password: ${MYSQL_PASSWORD-123456}
    host: ${MYSQL_ADDRESS-127.0.0.1}
    port: 3306
    db_name: ${MYSQL_DATABASE-test}
    charset: utf8mb4
    prefix: ims_
redis:
  default:
    host: 127.0.0.1
    port: 6379
    password:
    db: 0